/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    Canvas: typeof import('./components/Canvas/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageColorPickerPanel: typeof import('./components/Canvas/ImageColorPickerPanel.vue')['default']
    ImageCropOverlay: typeof import('./components/Canvas/ImageCropOverlay.vue')['default']
    ImageDialoguePanel: typeof import('./components/Canvas/ImageDialoguePanel.vue')['default']
    ImageGenNode: typeof import('./components/Canvas/nodes/ImageGenNode.vue')['default']
    ImageGenPromptPanel: typeof import('./components/Canvas/ImageGenPromptPanel.vue')['default']
    ImageGenSettingsPopover: typeof import('./components/Canvas/ImageGenSettingsPopover.vue')['default']
    ImageNode: typeof import('./components/Canvas/nodes/ImageNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextNode: typeof import('./components/Canvas/nodes/TextNode.vue')['default']
    VideoDialoguePanel: typeof import('./components/Canvas/VideoDialoguePanel.vue')['default']
    VideoFramesPanel: typeof import('./components/Canvas/VideoFramesPanel.vue')['default']
    VideoGenPromptPanel: typeof import('./components/Canvas/VideoGenPromptPanel.vue')['default']
    VideoGenSettingsPopover: typeof import('./components/Canvas/VideoGenSettingsPopover.vue')['default']
    VideoHdPanel: typeof import('./components/Canvas/VideoHdPanel.vue')['default']
    VideoNode: typeof import('./components/Canvas/nodes/VideoNode.vue')['default']
    VideoStoryboardPanel: typeof import('./components/Canvas/VideoStoryboardPanel.vue')['default']
  }
}
